name: CI Pipeline

on:
  push:
    branches: [ main, test, dev ]
  pull_request:
    branches: [ main, test, dev ]

jobs:
  setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      env-ready: ${{ steps.verify.outputs.ready }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Check flake
      run: nix flake check

    - name: Run linting
      run: nix develop --command python -m flake8 src/

    - name: Build ctag package
      run: nix build

    - name: Test built package
      run: nix develop --command ctag --help

    - name: Run tests
      run: nix develop --command python -m pytest
