name: CI Pipeline

on:
  push:
    branches: [ main, test, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      ATLASSIAN_URL: ${{ secrets.ATLASSIAN_URL }}
      ATLASSIAN_USERNAME: ${{ secrets.ATLASSIAN_USERNAME }}
      ATLASSIAN_TOKEN: ${{ secrets.ATLASSIAN_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Check flake
      run: nix flake check

    - name: Run Nix format
      run: nix fmt

    - name: Run linting
      run: nix develop --command python -m flake8 src/

    - name: Build ctag package
      run: nix build

    - name: Test built package
      run: nix develop --command ctag --help

    - name: Run tests
      run: nix develop --command python -m pytest -n auto --tb=short
