name: Setup Environment

on:
  push:
    branches: [ main, test, dev ]
  pull_request:
    branches: [ main, test, dev ]

jobs:
  setup-nix-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Setup development environment
      run: |
        echo "Setting up ctag development environment with Nix flake..."
        nix develop --command bash -c "
          echo 'Development environment setup complete!'
          echo 'Python version:' \$(python --version)
          echo 'ctag location:' \$(which ctag)
          echo 'Virtual environment:' \$(echo \$VIRTUAL_ENV)
          ctag --version
        "

    - name: Verify environment
      run: |
        echo "Verifying the environment is working..."
        nix develop --command bash -c "
          echo 'Running basic checks...'
          python -c 'import src.main; print(\"✓ ctag module imports successfully\")'
          ctag --help > /dev/null && echo '✓ ctag CLI works'
          python -m pytest --version > /dev/null && echo '✓ pytest available'
          echo 'Environment verification complete!'
        "
